"""
OCR_BHS - Processing Queue
===========================

Central thread-safe queues for asynchronous OCR and barcode processing.

Architecture:

    Live Pipeline
         |
         +---- OCR Task ------> OCR Queue ------> OCR Workers
         |
         +---- Barcode Task --> Barcode Queue -> Barcode Workers
                                      |
                                      v
                                Result Queue
                                      |
                                      v
                                Result Manager


IMPORTANT:
-----------
The live RTSP / YOLO / ByteTrack pipeline must NEVER wait for
OCR or barcode processing.

Therefore:
    submit_ocr()
    submit_barcode()

use put_nowait().

If a queue is full, the task is dropped instead of blocking
the camera/inference loop.
"""

from __future__ import annotations

import queue
import threading
from dataclasses import dataclass, field
from typing import Any, Optional


# =====================================================================
# OCR TASK
# =====================================================================


@dataclass
class OCRTask:
    """
    Task submitted to the asynchronous OCR pipeline.

    Parameters
    ----------
    task_id:
        Globally unique task identifier.

    camera_id:
        Camera that produced the frame.

    track_id:
        ByteTrack ID for this camera.

    frame:
        Image/frame to process.

    timestamp:
        Timestamp associated with the frame.

    frame_id:
        Frame number from the live camera/inference pipeline.
        Carried through to the result for end-to-end traceability
        (camera frame -> track -> task -> result -> DB row).

    metadata:
        Additional information such as:
            detection confidence
            bbox
            frame number
            camera timestamp
            best-frame score
            physical event information
    """

    task_id: str

    camera_id: str

    track_id: int

    frame: Any

    timestamp: float

    # Frame number from the live camera/inference pipeline.
    frame_id: Optional[int] = None

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


# =====================================================================
# BARCODE TASK
# =====================================================================


@dataclass
class BarcodeTask:
    """
    Task submitted to the asynchronous barcode pipeline.

    The frame is normally the best available IATA-tag image
    selected from the ByteTrack history.

    frame_id:
        Frame number from the live camera/inference pipeline.
        Carried through to the result for end-to-end traceability.
    """

    task_id: str

    camera_id: str

    track_id: int

    frame: Any

    timestamp: float

    # Frame number from the live camera/inference pipeline.
    frame_id: Optional[int] = None

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


# =====================================================================
# OCR RESULT
# =====================================================================


@dataclass
class OCRTaskResult:
    """
    Result generated by an OCR worker.

    frame_id:
        Propagated from the originating OCRTask so the result can
        be traced back to the exact camera frame without having to
        dig through metadata.
    """

    task_id: str

    camera_id: str

    track_id: int

    result: Any

    timestamp: float

    # Frame number propagated from the originating OCRTask.
    frame_id: Optional[int] = None

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


# =====================================================================
# BARCODE RESULT
# =====================================================================


@dataclass
class BarcodeTaskResult:
    """
    Result generated by a barcode worker.

    frame_id:
        Propagated from the originating BarcodeTask so the result can
        be traced back to the exact camera frame without having to
        dig through metadata.
    """

    task_id: str

    camera_id: str

    track_id: int

    result: Any

    timestamp: float

    # Frame number propagated from the originating BarcodeTask.
    frame_id: Optional[int] = None

    metadata: dict[str, Any] = field(
        default_factory=dict
    )


# =====================================================================
# PROCESSING QUEUE
# =====================================================================


class ProcessingQueue:
    """
    Central asynchronous processing queue.

    Queues
    ------

    OCR:
        live pipeline
            |
            v
        ocr_queue
            |
            v
        OCR workers

    Barcode:
        live pipeline
            |
            v
        barcode_queue
            |
            v
        Barcode workers

    Results:
        OCR / Barcode workers
            |
            v
        result_queue
            |
            v
        Result Manager


    Thread Safety
    ------------

    Python's queue.Queue is thread-safe.

    No additional locking is required for queue operations.

    A small Lock is used only for statistics.
    """

    def __init__(
        self,
        max_size: int = 50,
    ) -> None:

        # --------------------------------------------------------------
        # Validate queue size.
        # --------------------------------------------------------------

        self.max_size = max(
            1,
            int(max_size),
        )

        # --------------------------------------------------------------
        # OCR queue.
        #
        # Bounded queue prevents unlimited RAM usage.
        # --------------------------------------------------------------

        self.ocr_queue: queue.Queue[
            OCRTask
        ] = queue.Queue(
            maxsize=self.max_size
        )

        # --------------------------------------------------------------
        # Barcode queue.
        # --------------------------------------------------------------

        self.barcode_queue: queue.Queue[
            BarcodeTask
        ] = queue.Queue(
            maxsize=self.max_size
        )

        # --------------------------------------------------------------
        # Result queue.
        #
        # Both OCR and Barcode workers place their results here.
        # --------------------------------------------------------------

        self.result_queue: queue.Queue[
            OCRTaskResult | BarcodeTaskResult
        ] = queue.Queue(
            maxsize=self.max_size * 2
        )

        # --------------------------------------------------------------
        # Statistics lock.
        # --------------------------------------------------------------

        self._lock = threading.Lock()

        # --------------------------------------------------------------
        # OCR statistics.
        # --------------------------------------------------------------

        self._ocr_submitted = 0

        self._ocr_dropped = 0

        self._ocr_completed = 0

        # --------------------------------------------------------------
        # Barcode statistics.
        # --------------------------------------------------------------

        self._barcode_submitted = 0

        self._barcode_dropped = 0

        self._barcode_completed = 0

        # --------------------------------------------------------------
        # Result statistics.
        # --------------------------------------------------------------

        self._results_submitted = 0

        self._results_dropped = 0

        self._results_consumed = 0

        # --------------------------------------------------------------
        # Shutdown state.
        # --------------------------------------------------------------

        self._closed = False

    # =================================================================
    # OCR
    # =================================================================

    def submit_ocr(
        self,
        task: OCRTask,
    ) -> bool:
        """
        Submit an OCR task without blocking.

        Returns
        -------
        bool
            True:
                Task accepted.

            False:
                Queue is full or queue is closed.

        IMPORTANT
        ---------
        This method NEVER waits for a worker.

        This protects the live RTSP/inference pipeline.
        """

        if self._closed:

            with self._lock:
                self._ocr_dropped += 1

            return False

        try:

            self.ocr_queue.put_nowait(
                task
            )

            with self._lock:
                self._ocr_submitted += 1

            return True

        except queue.Full:

            with self._lock:
                self._ocr_dropped += 1

            return False

    # -----------------------------------------------------------------

    def get_ocr(
        self,
        timeout: float = 0.5,
    ) -> Optional[OCRTask]:
        """
        Retrieve an OCR task.

        Used by OCR worker threads.

        Parameters
        ----------
        timeout:
            Maximum time to wait for a task.

        Returns
        -------
        OCRTask | None
        """

        if self._closed and self.ocr_queue.empty():

            return None

        try:

            return self.ocr_queue.get(
                timeout=max(
                    0.0,
                    float(timeout),
                )
            )

        except queue.Empty:

            return None

    # -----------------------------------------------------------------

    def ocr_done(self) -> None:
        """
        Mark an OCR task as completed by a worker.

        This MUST be called exactly once for every task returned
        by get_ocr().
        """

        try:

            self.ocr_queue.task_done()

        except ValueError:

            # Defensive protection against incorrect worker
            # shutdown logic.
            pass

        with self._lock:

            self._ocr_completed += 1

    # =================================================================
    # BARCODE
    # =================================================================

    def submit_barcode(
        self,
        task: BarcodeTask,
    ) -> bool:
        """
        Submit a barcode task without blocking.

        Returns
        -------
        bool
            True:
                Task accepted.

            False:
                Queue full or queue closed.
        """

        if self._closed:

            with self._lock:
                self._barcode_dropped += 1

            return False

        try:

            self.barcode_queue.put_nowait(
                task
            )

            with self._lock:
                self._barcode_submitted += 1

            return True

        except queue.Full:

            with self._lock:
                self._barcode_dropped += 1

            return False

    # -----------------------------------------------------------------

    def get_barcode(
        self,
        timeout: float = 0.5,
    ) -> Optional[BarcodeTask]:
        """
        Retrieve a barcode task.

        Used by barcode worker threads.
        """

        if (
            self._closed
            and self.barcode_queue.empty()
        ):

            return None

        try:

            return self.barcode_queue.get(
                timeout=max(
                    0.0,
                    float(timeout),
                )
            )

        except queue.Empty:

            return None

    # -----------------------------------------------------------------

    def barcode_done(self) -> None:
        """
        Mark a barcode task as completed.
        """

        try:

            self.barcode_queue.task_done()

        except ValueError:

            pass

        with self._lock:

            self._barcode_completed += 1

    # =================================================================
    # RESULTS
    # =================================================================

    def submit_result(
        self,
        result: OCRTaskResult | BarcodeTaskResult,
    ) -> bool:
        """
        Submit a worker result without blocking.

        OCR and Barcode workers share the same result queue.

        The result object type tells the Result Manager what
        kind of result it received.
        """

        if self._closed:

            with self._lock:

                self._results_dropped += 1

            return False

        try:

            self.result_queue.put_nowait(
                result
            )

            with self._lock:

                self._results_submitted += 1

            return True

        except queue.Full:

            with self._lock:

                self._results_dropped += 1

            return False

    # -----------------------------------------------------------------

    def get_result(
        self,
        timeout: float = 0.1,
    ) -> Optional[
        OCRTaskResult | BarcodeTaskResult
    ]:
        """
        Retrieve a completed OCR or barcode result.

        Normally consumed by ResultManager.
        """

        if (
            self._closed
            and self.result_queue.empty()
        ):

            return None

        try:

            return self.result_queue.get(
                timeout=max(
                    0.0,
                    float(timeout),
                )
            )

        except queue.Empty:

            return None

    # -----------------------------------------------------------------

    def result_done(self) -> None:
        """
        Mark a result as consumed.
        """

        try:

            self.result_queue.task_done()

        except ValueError:

            pass

        with self._lock:

            self._results_consumed += 1

    # =================================================================
    # QUEUE SIZES
    # =================================================================

    @property
    def ocr_size(self) -> int:
        """
        Number of OCR tasks currently waiting.
        """

        return self.ocr_queue.qsize()

    # -----------------------------------------------------------------

    @property
    def barcode_size(self) -> int:
        """
        Number of barcode tasks currently waiting.
        """

        return self.barcode_queue.qsize()

    # -----------------------------------------------------------------

    @property
    def result_size(self) -> int:
        """
        Number of results currently waiting.
        """

        return self.result_queue.qsize()

    # =================================================================
    # FULL STATUS
    # =================================================================

    def status(self) -> dict[str, Any]:
        """
        Return complete queue statistics.

        Useful for logging and future monitoring.
        """

        with self._lock:

            return {

                "closed": self._closed,

                # --------------------------------------------------
                # Queue capacities
                # --------------------------------------------------

                "max_queue_size": (
                    self.max_size
                ),

                "max_result_queue_size": (
                    self.max_size * 2
                ),

                # --------------------------------------------------
                # Current queue sizes
                # --------------------------------------------------

                "ocr_pending": (
                    self.ocr_queue.qsize()
                ),

                "barcode_pending": (
                    self.barcode_queue.qsize()
                ),

                "result_pending": (
                    self.result_queue.qsize()
                ),

                # --------------------------------------------------
                # OCR
                # --------------------------------------------------

                "ocr_submitted": (
                    self._ocr_submitted
                ),

                "ocr_dropped": (
                    self._ocr_dropped
                ),

                "ocr_completed": (
                    self._ocr_completed
                ),

                # --------------------------------------------------
                # Barcode
                # --------------------------------------------------

                "barcode_submitted": (
                    self._barcode_submitted
                ),

                "barcode_dropped": (
                    self._barcode_dropped
                ),

                "barcode_completed": (
                    self._barcode_completed
                ),

                # --------------------------------------------------
                # Results
                # --------------------------------------------------

                "results_submitted": (
                    self._results_submitted
                ),

                "results_dropped": (
                    self._results_dropped
                ),

                "results_consumed": (
                    self._results_consumed
                ),

                # --------------------------------------------------
                # Queue state
                # --------------------------------------------------

                "ocr_full": (
                    self.ocr_queue.full()
                ),

                "barcode_full": (
                    self.barcode_queue.full()
                ),

                "result_full": (
                    self.result_queue.full()
                ),
            }

    # =================================================================
    # EMPTY CHECKS
    # =================================================================

    def is_ocr_empty(self) -> bool:

        return self.ocr_queue.empty()

    # -----------------------------------------------------------------

    def is_barcode_empty(self) -> bool:

        return self.barcode_queue.empty()

    # -----------------------------------------------------------------

    def is_result_empty(self) -> bool:

        return self.result_queue.empty()

    # =================================================================
    # FULL CHECKS
    # =================================================================

    def is_ocr_full(self) -> bool:

        return self.ocr_queue.full()

    # -----------------------------------------------------------------

    def is_barcode_full(self) -> bool:

        return self.barcode_queue.full()

    # -----------------------------------------------------------------

    def is_result_full(self) -> bool:

        return self.result_queue.full()

    # =================================================================
    # WAIT FOR QUEUES
    # =================================================================

    def wait_for_ocr(
        self,
        timeout: Optional[float] = None,
    ) -> bool:
        """
        Wait until all queued OCR tasks have been processed.

        This method is intended for controlled shutdown/testing.

        DO NOT call this from the live camera processing loop.
        """

        try:

            if timeout is None:

                self.ocr_queue.join()

                return True

            # queue.Queue.join() itself has no timeout.
            #
            # Poll unfinished_tasks instead.

            deadline = (
                threading.current_thread()
            )

            # The variable above intentionally avoids
            # importing another timing module for the normal
            # queue operation.

            import time

            end_time = (
                time.monotonic()
                + max(
                    0.0,
                    float(timeout),
                )
            )

            while True:

                if (
                    self.ocr_queue
                    .unfinished_tasks
                    == 0
                ):

                    return True

                if (
                    time.monotonic()
                    >= end_time
                ):

                    return False

                time.sleep(
                    0.01
                )

        except Exception:

            return False

    # -----------------------------------------------------------------

    def wait_for_barcode(
        self,
        timeout: Optional[float] = None,
    ) -> bool:
        """
        Wait until all queued barcode tasks are processed.

        Intended for testing/shutdown only.
        """

        try:

            if timeout is None:

                self.barcode_queue.join()

                return True

            import time

            end_time = (
                time.monotonic()
                + max(
                    0.0,
                    float(timeout),
                )
            )

            while True:

                if (
                    self.barcode_queue
                    .unfinished_tasks
                    == 0
                ):

                    return True

                if (
                    time.monotonic()
                    >= end_time
                ):

                    return False

                time.sleep(
                    0.01
                )

        except Exception:

            return False

    # -----------------------------------------------------------------

    def wait_for_results(
        self,
        timeout: Optional[float] = None,
    ) -> bool:
        """
        Wait until all queued results are consumed.

        Intended for controlled shutdown/testing only.
        """

        try:

            if timeout is None:

                self.result_queue.join()

                return True

            import time

            end_time = (
                time.monotonic()
                + max(
                    0.0,
                    float(timeout),
                )
            )

            while True:

                if (
                    self.result_queue
                    .unfinished_tasks
                    == 0
                ):

                    return True

                if (
                    time.monotonic()
                    >= end_time
                ):

                    return False

                time.sleep(
                    0.01
                )

        except Exception:

            return False

    # =================================================================
    # CLEAR OCR
    # =================================================================

    def clear_ocr(self) -> int:
        """
        Remove all pending OCR tasks.

        Returns
        -------
        int
            Number of removed tasks.
        """

        removed = 0

        while True:

            try:

                self.ocr_queue.get_nowait()

                try:

                    self.ocr_queue.task_done()

                except ValueError:
                    pass

                removed += 1

            except queue.Empty:

                break

        return removed

    # =================================================================
    # CLEAR BARCODE
    # =================================================================

    def clear_barcode(self) -> int:
        """
        Remove all pending barcode tasks.
        """

        removed = 0

        while True:

            try:

                self.barcode_queue.get_nowait()

                try:

                    self.barcode_queue.task_done()

                except ValueError:
                    pass

                removed += 1

            except queue.Empty:

                break

        return removed

    # =================================================================
    # CLEAR RESULTS
    # =================================================================

    def clear_results(self) -> int:
        """
        Remove all pending results.
        """

        removed = 0

        while True:

            try:

                self.result_queue.get_nowait()

                try:

                    self.result_queue.task_done()

                except ValueError:
                    pass

                removed += 1

            except queue.Empty:

                break

        return removed

    # =================================================================
    # CLEAR ALL
    # =================================================================

    def clear(self) -> dict[str, int]:
        """
        Clear all pending work.

        Returns number of removed items.
        """

        return {

            "ocr": self.clear_ocr(),

            "barcode": self.clear_barcode(),

            "results": self.clear_results(),
        }

    # =================================================================
    # CLOSE
    # =================================================================

    def close(
        self,
        clear_pending: bool = False,
    ) -> None:
        """
        Close the queue.

        New tasks will no longer be accepted.

        Parameters
        ----------
        clear_pending:
            If True, pending tasks/results are removed.

            If False, workers can finish remaining tasks before
            shutdown.
        """

        self._closed = True

        if clear_pending:

            self.clear()

    # =================================================================
    # REOPEN
    # =================================================================

    def reopen(self) -> None:
        """
        Reopen the queue.

        Normally used only during testing/restart.
        """

        self._closed = False

    # =================================================================
    # CLOSED
    # =================================================================

    @property
    def closed(self) -> bool:

        return self._closed


# =====================================================================
# STANDALONE TEST
# =====================================================================


def main() -> None:

    import time

    print()
    print("=" * 70)
    print("OCR_BHS - PROCESSING QUEUE TEST")
    print("=" * 70)

    # --------------------------------------------------------------
    # Create queue
    # --------------------------------------------------------------

    processing_queue = ProcessingQueue(
        max_size=3
    )

    print()
    print("Initial status:")
    print(
        processing_queue.status()
    )

    # --------------------------------------------------------------
    # OCR test
    # --------------------------------------------------------------

    print()
    print("Submitting OCR tasks...")

    for index in range(5):

        task = OCRTask(
            task_id=f"ocr-test-{index}",
            camera_id="camera_1",
            track_id=index + 1,
            frame=None,
            timestamp=time.time(),
            frame_id=index,
            metadata={
                "test": True,
            },
        )

        accepted = (
            processing_queue.submit_ocr(
                task
            )
        )

        print(
            f"OCR task {index}: "
            f"{'ACCEPTED' if accepted else 'DROPPED'}"
        )

    # --------------------------------------------------------------
    # Barcode test
    # --------------------------------------------------------------

    print()
    print("Submitting barcode tasks...")

    for index in range(5):

        task = BarcodeTask(
            task_id=f"barcode-test-{index}",
            camera_id="camera_1",
            track_id=index + 1,
            frame=None,
            timestamp=time.time(),
            frame_id=index,
            metadata={
                "test": True,
            },
        )

        accepted = (
            processing_queue
            .submit_barcode(
                task
            )
        )

        print(
            f"Barcode task {index}: "
            f"{'ACCEPTED' if accepted else 'DROPPED'}"
        )

    # --------------------------------------------------------------
    # Status
    # --------------------------------------------------------------

    print()
    print("Queue status:")

    print(
        processing_queue.status()
    )

    # --------------------------------------------------------------
    # Retrieve OCR task
    # --------------------------------------------------------------

    ocr_task = (
        processing_queue.get_ocr(
            timeout=0.1
        )
    )

    if ocr_task:

        print()
        print(
            "Retrieved OCR task:"
        )

        print(
            f"  task_id  : "
            f"{ocr_task.task_id}"
        )

        processing_queue.ocr_done()

    # --------------------------------------------------------------
    # Retrieve barcode task
    # --------------------------------------------------------------

    barcode_task = (
        processing_queue.get_barcode(
            timeout=0.1
        )
    )

    if barcode_task:

        print()
        print(
            "Retrieved Barcode task:"
        )

        print(
            f"  task_id  : "
            f"{barcode_task.task_id}"
        )

        processing_queue.barcode_done()

    # --------------------------------------------------------------
    # Result test
    # --------------------------------------------------------------

    print()
    print("Submitting result...")

    result = OCRTaskResult(
        task_id="ocr-result-1",
        camera_id="camera_1",
        track_id=1,
        result={
            "text": "TEST-IATA",
        },
        timestamp=time.time(),
        frame_id=0,
        metadata={
            "test": True,
        },
    )

    accepted = (
        processing_queue
        .submit_result(
            result
        )
    )

    print(
        "Result:",
        "ACCEPTED"
        if accepted
        else "DROPPED",
    )

    # --------------------------------------------------------------
    # Retrieve result
    # --------------------------------------------------------------

    received = (
        processing_queue.get_result(
            timeout=0.1
        )
    )

    if received:

        print()
        print(
            "Retrieved result:"
        )

        print(
            f"  task_id  : "
            f"{received.task_id}"
        )

        print(
            f"  camera   : "
            f"{received.camera_id}"
        )

        print(
            f"  track_id : "
            f"{received.track_id}"
        )

        print(
            f"  frame_id : "
            f"{received.frame_id}"
        )

        processing_queue.result_done()

    # --------------------------------------------------------------
    # Final status
    # --------------------------------------------------------------

    print()
    print("Final status:")

    print(
        processing_queue.status()
    )

    # --------------------------------------------------------------
    # Close
    # --------------------------------------------------------------

    processing_queue.close(
        clear_pending=True
    )

    print()
    print(
        "Queue closed."
    )

    print()
    print("=" * 70)
    print("PROCESSING QUEUE TEST COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    main()